twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        destination_repository: '@App\Repository\DestinationRepository'

when@test:
    twig:
        strict_variables: true
