vich_uploader:
    db_driver: orm

    mappings:
        conseiller:
            uri_prefix: /images/conseillers
            upload_destination: '%kernel.project_dir%/public/images/conseillers'
        etape:
            uri_prefix: /images/etapes
            upload_destination: '%kernel.project_dir%/public/images/etapes'
        produit:
            uri_prefix: /images/produits
            upload_destination: '%kernel.project_dir%/public/images/produits'
